name: "Process Content"
description: "Processes new content to be created on Trybe"
inputs:
  token:
    description: "The GitHub token to use for checkout on git"
    required: true
  path:
    description: "The directory path of files to be processed"
    required: true
outputs:
  result:
    description: "The message to output"
runs:
  using: "node12"
  main: "dist/index.js"
