name: "Process Content"
description: "Processes new content to be created on Trybe"
inputs:
  apiKey:
    description: "The Key for access on Trybe Api"
    required: true
  apiUrl:
    description: "Trybe Application env URL to access"
    required: true 
  dirPath:
    description: "The directory path of files to be processed"
    required: true
outputs:
  result:
    description: "The message to output"
runs:
  using: "node12"
  main: "dist/index.js"
