name: "Process Content"
description: "Processes new content to be created on Trybe"
inputs:
  token:
    description: "The Github Token for checkout on repo"
    required: true
  apiKey:
    description: "The Key for access on Trybe Api"
    required: true
  chapterApiURL:
    description: "Trybe Application Chapter env URL to access"
    required: true
  versionApiURL:
    description: "Trybe Application Version env URL to access"
    required: true
  applicationHealthApiURL:
    description: "Heroku Trybe Application env URL to health check"
    required: true
  contentPath:
    description: "The directory path of content files to be processed"
    required: true
  assetPath:
    description: "The directory path of asset files to be processed"
    required: true
  awsAccessKey:
    description: "The aws key to authenticate via sdk"
    required: true
  awsSecret:
    description: "The aws secret to authenticate via sdk"
    required: true
  bucketName:
    description: "The aws bucket name for uploading assets"
    required: true
  pullRequestMergedAt:
    description: "Time stamp data of when the PR was merged"
    required: true
  pullRequestMergeCommitId:
    description: "Commit sha from merge that triggered the action"
    required: true
  pullRequestId:
    description: "Pull request number that triggered the action"
    required: true
  chunkSize:
    description: "Size of group of files to be sent to chapter creation"
    required: true
  intervalBetweenChunks:
    description: "Interval in milliseconds between each group of chapter creation requests"
    required: true
  healthCheckInterval:
    description: "Interval in milliseconds between each retry on content api health_check"
    required: false
  maxServiceRetry:
    description: "Maximum of retries action would be doing to content api to check if it is up"
    required: false

outputs:
  result:
    description: "The message to output"
runs:
  using: "node12"
  main: "dist/index.js"
