name: "Automated Tests"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  eslint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: '12'
      - name: install dependencies
        run: npm i
      - name: run eslint
        run: npx eslint .

  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: npm i
    - name: run jest tests
    - run: npm test

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ${{ secrets.FILES_PATH}}
        apiKey: ${{ secrets.TRYBE_API_KEY}}
        apiUrl:  ${{ secrets.TRYBE_API_URL}}
