name: "Automated Tests"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: '12'
      - name: install dependencies
        run: npm i
      - name: run eslint
        run: npx eslint .

  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: npm i
    - name: run jest tests
      run: npm test
